### ISSUE TITLE
gensim的similarities缓存文件无法保存

### ISSUE THREAD

**Issue by sz-code** [EndlessLethe/dataeda#5]
![image](https://user-images.githubusercontent.com/52724781/84976765-50905d00-b15b-11ea-9861-1948a36cf3bd.png)
麻烦您 看一下这个问题怎么解决

**Comment by EndlessLethe** [comment]
Please check your local setting with Gensim document. If still confused, search in Google. 
Here may be some api changes because this repo is no longer maintained.
Thanks!
